const defaultEvents = [
    {
        id: 1,
        title: 'Interview - Backend Engineer',
        start: new Date(),
        className: 'bg-success',
        idCategoria: '',
        titleCategoria: '',
        idDocente: 1,
    },
    {
        id: 2,
        title: 'Phone Screen - Frontend Engineer',
        start: new Date().setDate(new Date().getDate() + 2),
        className: 'bg-info',
        idCategoria: '',
        titleCategoria: '',
        idDocente: 2,
    },
    {
        id: 3,
        title: 'Meeting with John Deo',
        start: new Date().setDate(new Date().getDate() + 2),
        end: new Date().setDate(new Date().getDate() + 4),
        className: 'bg-warning',
        idCategoria: '',
        titleCategoria: '',
        idDocente: 2,
    },
    {
        id: 4,
        title: 'Buy a Theme',
        start: new Date().setDate(new Date().getDate() + 4),
        end: new Date().setDate(new Date().getDate() + 5),
        className: 'bg-primary',
        idCategoria: '',
        titleCategoria: '',
        idDocente: 2,
    },
];
const docentes = [
  {
      id: 1,
      name: 'Abagael Breslau',
      phone: '(461) 3636077',
      email: 'abreslau0@wiley.com',
      location: 'China',
      created_on: '7/4/2019',
      status: 'Active',
      avatar: 'https://robohash.org/laborevoluptateeaque.png?size=60x60&set=set1',
  },
  {
      id: 2,
      name: 'Veradis Taber',
      phone: '(917) 2590629',
      email: 'vtaber1@ucoz.com',
      location: 'Venezuela',
      created_on: '7/8/2019',
      status: 'Active',
      avatar: 'https://robohash.org/voluptatemeligendisint.png?size=60x60&set=set1',
  },
  {
      id: 3,
      name: 'Lindon Ceeley',
      phone: '(925) 9515307',
      email: 'lceeley2@fotki.com',
      location: 'Panama',
      created_on: '7/20/2019',
      status: 'Active',
      avatar: 'https://robohash.org/etidsapiente.png?size=60x60&set=set1',
  },
  {
      id: 4,
      name: 'Mendel Alfonzo',
      phone: '(295) 3668262',
      email: 'malfonzo3@irs.gov',
      location: 'France',
      created_on: '7/22/2019',
      status: 'Active',
      avatar: 'https://robohash.org/pariaturharumquas.png?size=60x60&set=set1',
  },
  {
      id: 5,
      name: 'Dorrie Tindley',
      phone: '(809) 2120936',
      email: 'dtindley4@so-net.ne.jp',
      location: 'Colombia',
      created_on: '7/14/2019',
      status: 'Blocked',
      avatar: 'https://robohash.org/quodfugiatquae.png?size=60x60&set=set1',
  },
  {
      id: 6,
      name: 'Kata MacKnight',
      phone: '(402) 3164595',
      email: 'kmacknight5@boston.com',
      location: 'China',
      created_on: '7/10/2019',
      status: 'Active',
      avatar: 'https://robohash.org/sapientenonomnis.png?size=60x60&set=set1',
  },
  {
      id: 7,
      name: 'Mateo Kingzeth',
      phone: '(941) 2564726',
      email: 'mkingzeth6@google.com.hk',
      location: 'China',
      created_on: '7/18/2019',
      status: 'Active',
      avatar: 'https://robohash.org/autvelitest.png?size=60x60&set=set1',
  },
  {
      id: 8,
      name: 'Jayson Creaney',
      phone: '(969) 3198297',
      email: 'jcreaney7@netvibes.com',
      location: 'Malaysia',
      created_on: '7/19/2019',
      status: 'Blocked',
      avatar: 'https://robohash.org/exsuscipitcorporis.png?size=60x60&set=set1',
  },
  {
      id: 9,
      name: 'Elita Ortmann',
      phone: '(283) 1302865',
      email: 'eortmann8@pinterest.com',
      location: 'South Korea',
      created_on: '7/2/2019',
      status: 'Blocked',
      avatar: 'https://robohash.org/consectetureiuset.png?size=60x60&set=set1',
  },
  {
      id: 10,
      name: 'Tyne Hollidge',
      phone: '(529) 2241787',
      email: 'thollidge9@ebay.co.uk',
      location: 'China',
      created_on: '7/11/2019',
      status: 'Active',
      avatar: 'https://robohash.org/aspernaturlaborumab.png?size=60x60&set=set1',
  },
  {
      id: 11,
      name: 'Ezmeralda Piggrem',
      phone: '(532) 2561412',
      email: 'epiggrema@addtoany.com',
      location: 'Cambodia',
      created_on: '7/6/2019',
      status: 'Blocked',
      avatar: 'https://robohash.org/veroinciduntfacere.png?size=60x60&set=set1',
  },
  {
      id: 12,
      name: 'Kalina Dabels',
      phone: '(953) 8150340',
      email: 'kdabelsb@typepad.com',
      location: 'Mexico',
      created_on: '7/16/2019',
      status: 'Active',
      avatar: 'https://robohash.org/cumvoluptatibusreprehenderit.png?size=60x60&set=set1',
  },
  {
      id: 13,
      name: 'Claudianus Gommes',
      phone: '(791) 6099303',
      email: 'cgommesc@berkeley.edu',
      location: 'Indonesia',
      created_on: '7/14/2019',
      status: 'Active',
      avatar: 'https://robohash.org/sitlaboreet.png?size=60x60&set=set1',
  },
  {
      id: 14,
      name: 'Ulrikaumeko Jentle',
      phone: '(478) 8204063',
      email: 'ujentled@pagesperso-orange.fr',
      location: 'Sweden',
      created_on: '7/25/2019',
      status: 'Active',
      avatar: 'https://robohash.org/placeateligendiexcepturi.png?size=60x60&set=set1',
  },
  {
      id: 15,
      name: 'Peria Richens',
      phone: '(423) 7419337',
      email: 'prichense@google.it',
      location: 'Indonesia',
      created_on: '7/20/2019',
      status: 'Blocked',
      avatar: 'https://robohash.org/impeditreprehenderiteos.png?size=60x60&set=set1',
  },
  {
      id: 16,
      name: 'Sollie Ramelet',
      phone: '(600) 7539738',
      email: 'srameletf@hubpages.com',
      location: 'Brazil',
      created_on: '7/3/2019',
      status: 'Blocked',
      avatar: 'https://robohash.org/quodeased.png?size=60x60&set=set1',
  },
  {
      id: 17,
      name: 'Hodge Diviney',
      phone: '(311) 8358001',
      email: 'hdivineyg@ycombinator.com',
      location: 'Belarus',
      created_on: '7/28/2019',
      status: 'Blocked',
      avatar: 'https://robohash.org/ipsaprovidentmaiores.png?size=60x60&set=set1',
  },
  {
      id: 18,
      name: 'Roger Lidster',
      phone: '(146) 1370107',
      email: 'rlidsterh@redcross.org',
      location: 'Indonesia',
      created_on: '7/5/2019',
      status: 'Blocked',
      avatar: 'https://robohash.org/corruptiomnisearum.png?size=60x60&set=set1',
  },
  {
      id: 19,
      name: 'Caprice Custed',
      phone: '(239) 8054555',
      email: 'ccustedi@godaddy.com',
      location: 'Russia',
      created_on: '7/14/2019',
      status: 'Active',
      avatar: 'https://robohash.org/itaquesedvoluptate.png?size=60x60&set=set1',
  },
  {
      id: 20,
      name: 'Becki Filer',
      phone: '(128) 9346017',
      email: 'bfilerj@xrea.com',
      location: 'Madagascar',
      created_on: '7/11/2019',
      status: 'Blocked',
      avatar: 'https://robohash.org/autillonam.png?size=60x60&set=set1',
  },
  {
      id: 21,
      name: 'Rube Sjostrom',
      phone: '(216) 7061924',
      email: 'rsjostromk@blogger.com',
      location: 'France',
      created_on: '7/28/2019',
      status: 'Blocked',
      avatar: 'https://robohash.org/quasiexercitationemvel.png?size=60x60&set=set1',
  },
  {
      id: 22,
      name: 'Gris Biggin',
      phone: '(269) 4756082',
      email: 'gbigginl@usa.gov',
      location: 'Indonesia',
      created_on: '7/27/2019',
      status: 'Active',
      avatar: 'https://robohash.org/quosaliquamcorrupti.png?size=60x60&set=set1',
  },
  {
      id: 23,
      name: 'Les Blain',
      phone: '(138) 1015423',
      email: 'lblainm@wsj.com',
      location: 'China',
      created_on: '7/21/2019',
      status: 'Active',
      avatar: 'https://robohash.org/velexcepturidignissimos.png?size=60x60&set=set1',
  },
  {
      id: 24,
      name: 'Adelaida MacWhan',
      phone: '(396) 7710932',
      email: 'amacwhann@abc.net.au',
      location: 'Nigeria',
      created_on: '7/27/2019',
      status: 'Blocked',
      avatar: 'https://robohash.org/nonveroprovident.png?size=60x60&set=set1',
  },
  {
      id: 25,
      name: 'Marco Capon',
      phone: '(315) 8620366',
      email: 'mcapono@ucla.edu',
      location: 'China',
      created_on: '7/1/2019',
      status: 'Active',
      avatar: 'https://robohash.org/eumevenietqui.png?size=60x60&set=set1',
  },
  {
      id: 26,
      name: 'Cordula Goude',
      phone: '(244) 8639717',
      email: 'cgoudep@indiatimes.com',
      location: 'China',
      created_on: '7/4/2019',
      status: 'Active',
      avatar: 'https://robohash.org/estvoluptatesed.png?size=60x60&set=set1',
  },
  {
      id: 27,
      name: 'Pippa Piken',
      phone: '(440) 3470724',
      email: 'ppikenq@vistaprint.com',
      location: 'Peru',
      created_on: '7/23/2019',
      status: 'Blocked',
      avatar: 'https://robohash.org/quianimiquis.png?size=60x60&set=set1',
  },
  {
      id: 28,
      name: 'Katharina Snell',
      phone: '(252) 7933179',
      email: 'ksnellr@spiegel.de',
      location: 'Sierra Leone',
      created_on: '7/7/2019',
      status: 'Blocked',
      avatar: 'https://robohash.org/reiciendisquisquamnemo.png?size=60x60&set=set1',
  },
  {
      id: 29,
      name: 'Friedrich Brickner',
      phone: '(909) 3774612',
      email: 'fbrickners@nba.com',
      location: 'Taiwan',
      created_on: '7/19/2019',
      status: 'Active',
      avatar: 'https://robohash.org/autemharummolestiae.png?size=60x60&set=set1',
  }

];
export { defaultEvents,docentes };
