    const REFERENCIAS_ITEMS = [
        {
            IdBasket:1,
            title:"# 1  REFERENCIA 001",
            inventario:"23",
            estado:"bg-danger",
            description:"CANASTA DE LAPAROTOMIA ADULTO",
            textClass: 'badge bg-info',
            icon: 'mdi mdi-arrow-down-bold',
            stock: '50',
            time: 'Since last month',
        },{
            IdBasket:2,
            title:"# 2  REFERENCIA 002",
            inventario:"23",
            estado:"bg-danger",
            description:"CANASTA DE LAPAROTOMIA ADULTO",
            textClass: 'badge bg-info',
            icon: 'mdi mdi-arrow-down-bold',
            stock: '50',
            time: 'Since last month',
        },{
            IdBasket:3,      
            title:"# 3  REFERENCIA 003",
            inventario:"23",
            estado:"bg-danger",
            description:" CANASTA DE MEDIANA",
            textClass: 'badge bg-info',
            icon: 'mdi mdi-arrow-down-bold',
            stock: '50',
            time: 'Since last month',
        },{
            IdBasket:4,       
            title:"# 4  REFERENCIA 004",
            inventario:"23",
            estado:"bg-danger",
            description:" CANASTA DE LAPAROTOMIA INFANTIL",
            textClass: 'badge bg-info',
            icon: 'mdi mdi-arrow-down-bold',
            stock: '50',
            time: 'Since last month',
        },{
            IdBasket:5,       
            title:"# 5  REFERENCIA 005",
            inventario:"23",
            estado:"bg-danger",
            description:"CANASTA DE ORTOPEDIA",
            textClass: 'badge bg-info',
            icon: 'mdi mdi-arrow-down-bold',
            stock: '50',
            time: 'Since last month',
        },{
            IdBasket:6,       
            title:"# 6  REFERENCIA 006",
            inventario:"23",
            estado:"bg-danger",
            description:"CANASTA DE TORAX",
            textClass: 'badge bg-info',
            icon: 'mdi mdi-arrow-down-bold',
            stock: '50',
            time: 'Since last month',
        },{
            IdBasket:7,      
            title:"# 7  REFERENCIA 007",
            inventario:"23",
            estado:"bg-danger",
            description:"CANASTA VASCULAR GENERAL",
            textClass: 'badge bg-info',
            icon: 'mdi mdi-arrow-down-bold',
            stock: '50',
            time: 'Since last month',
        },{
            IdBasket:8,        
            title:"# 8  REFERENCIA 008",
            inventario:"23",
            estado:"bg-danger",
            description:"CANASTA VASCULAR PERIFERICO",
            textClass: 'badge bg-info',
            icon: 'mdi mdi-arrow-down-bold',
            stock: '50',
            time: 'Since last month',
        },{
            IdBasket:9,        
            title:"# 8  REFERENCIA 009",
            inventario:"23",
            estado:"bg-danger",
            description:"CANASTA DE OTORRINOLARINGOLOGIA",
            textClass: 'badge bg-info',
            icon: 'mdi mdi-arrow-down-bold',
            stock: '50',
            time: 'Since last month',
        },{
            IdBasket:10,        
            title:"# 10  REFERENCIA 010",
            inventario:"23",
            estado:"bg-danger",
            description:"CANASTA DE MICROCIRUGIA (NEUROCIRUGIA)",
            textClass: 'badge bg-info',
            icon: 'mdi mdi-arrow-down-bold',
            stock: '50',
            time: 'Since last month',
        },{
            IdBasket:11,        
            title:"# 11  REFERENCIA 011",
            inventario:"23",
            estado:"bg-danger",
            description:"CANASTA DE CIERRE DE HERIDAS",
            textClass: 'badge bg-info',
            icon: 'mdi mdi-arrow-down-bold',
            stock: '50',
            time: 'Since last month',
        },{
            IdBasket:12,
            title:"# 12  REFERENCIA 012",
            inventario:"23",
            estado:"bg-danger",
            description:"CANASTA DE CIERRE DE HERIDAS",
            textClass: 'badge bg-info',
            icon: 'mdi mdi-arrow-down-bold',
            stock: '50',
            time: 'Since last month',
        },{
            IdBasket:13,	
            title:"# 13  REFERENCIA 013",
            inventario:"23",
            estado:"bg-danger",
            description:"CANASTA GINECOLOGICA",
            textClass: 'badge bg-info',
            icon: 'mdi mdi-arrow-down-bold',
            stock: '50',
            time: 'Since last month',
        },{
            IdBasket:14,        
            title:"# 14  REFERENCIA 014",
            inventario:"23",
            estado:"bg-danger",
            description:"CANASTA NEUROCIRUGIA",
            textClass: 'badge bg-info',
            icon: 'mdi mdi-arrow-down-bold',
            stock: '50',
            time: 'Since last month',
        },{
            IdBasket:15,	
            title:"# 15  REFERENCIA 015",
            inventario:"23",
            estado:"bg-danger",
            description:"CANASTA GINECOLOGIA VAGINAL",
            textClass: 'badge bg-info',
            icon: 'mdi mdi-arrow-down-bold',
            stock: '50',
            time: 'Since last month',
        },{
            IdBasket:16,	
            title:"# 16 REFERENCIA 016",
            inventario:"23",
            estado:"bg-danger",
            description:"CANASTA UROLOGIA",
            textClass: 'badge bg-info',
            icon: 'mdi mdi-arrow-down-bold',
            stock: '50',
            time: 'Since last month',
        },{
            IdBasket:17,	
            title:"# 17  REFERENCIA 017",
            inventario:"23",
            estado:"bg-danger",
            description:"CANASTA DE PEQUEÑA CIRUGIA",
            textClass: 'badge bg-info',
            icon: 'mdi mdi-arrow-down-bold',
            stock: '50',
            time: 'Since last month',
        },{
            IdBasket:18,	
            title:"# 18  REFERENCIA 018",
            inventario:"23",
            estado:"bg-danger",
            description:"CANASTA OFTALMOLOGIA",
            textClass: 'badge bg-info',
            icon: 'mdi mdi-arrow-down-bold',
            stock: '50',
            time: 'Since last month',
        },{
            IdBasket:19,	
            title:"# 19  REFERENCIA 018",
            inventario:"23",
            estado:"bg-danger",
            description:"CANASTA DE VIAS BILIARES",
            textClass: 'badge bg-info',
            icon: 'mdi mdi-arrow-down-bold',
            stock: '50',
            time: 'Since last month',
        },{
            IdBasket:20,	
            title:"# 20  REFERENCIA 020",
            inventario:"23",
            estado:"bg-danger",
            description:"CANASTA DE CLANES INTESTINALES",
            textClass: 'badge bg-info',
            icon: 'mdi mdi-arrow-down-bold',
            stock: '50',
            time: 'Since last month',
        },{
            IdBasket:21,	
            title:"# 21  REFERENCIA 021",
            inventario:"23",
            estado:"bg-danger",
            description:"CANASTA DE PROCTOLOGIA",
            textClass: 'badge bg-info',
            icon: 'mdi mdi-arrow-down-bold',
            stock: '50',
            time: 'Since last month',
        },{
            IdBasket:22,	
            title:"# 22  REFERENCIA 022",
            inventario:"23",
            estado:"bg-danger",
            description:"SISTEMA  DE 3,5 MM",
            textClass: 'badge bg-info',
            icon: 'mdi mdi-arrow-down-bold',
            stock: '50',
            time: 'Since last month',
        },{
            IdBasket:23,
            title:"# 23  REFERENCIA 023",
            inventario:"23",
            estado:"bg-danger",
            description:"PERFORADOR CANULADO",
            textClass: 'badge bg-info',
            icon: 'mdi mdi-arrow-down-bold',
            stock: '50',
            time: 'Since last month',
        },{
            IdBasket:24,
            title:"# 24  REFERENCIA 024",
            inventario:"23",
            estado:"bg-danger",
            description:"TELEVISOR INTERACTIVO",
            textClass: 'badge bg-info',
            icon: 'mdi mdi-arrow-down-bold',
            stock: '50',
            time: 'Since last month',
        },{
            IdBasket:25,
            title:"# 25  REFERENCIA 025",
            inventario:"23",
            estado:"bg-danger",
            description:"SIMULADOR DE LAPAROSCOPIA",
            textClass: 'badge bg-info',
            icon: 'mdi mdi-arrow-down-bold',
            stock: '50',
            time: 'Since last month',
        }
        ];
export {REFERENCIAS_ITEMS};
